### PR TITLE
Complete customizations

### PR DESCRIPTION
**Pull request by julieces**

### CODE REVIEW

**Comment by joannakl** [comment]
@julieces 
You should have the push permissions for this repository, so just write to it directly! I should have mentioned this in class, I guess.

**Comment by julieces** [comment]
When I started to edit it, it said that I didn't have permissions and it forked the repo

**Comment by joannakl** [comment]
Hmm. Not sure what you are doing that is different. There is another student in the class who was able to edit her repo directly and I just tested it with my own fake-student account. 
Were you logged in as julieces when you started to edit, or did you need to login when you created the fork?

**Comment by julieces** [comment]
Do you want me to come to your office tomorrow and look at it? Or we can
just talk after class on Wednesday.

**Pull request merged**
